# Generated by Django 5.0.1 on 2024-01-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0003_kit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='content',
        ),
        migrations.AddField(
            model_name='kit',
            name='content',
            field=models.ManyToManyField(related_name='kit_content', to='bigbox.product'),
        ),
    ]
