# Generated by Django 5.0.1 on 2024-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bigbox", "0004_remove_kit_content_kit_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="cost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="kit",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="kit",
            name="profit",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
